Repository quantopian/trading_calendars, pull requests merged in 2020-10, with the labels that each got.

#165 ENH: Update XHKG calendar
  tests/resources/xhkg.csv
  tests/test_xhkg_calendar.py
  trading_calendars/common_holidays.py
  trading_calendars/exchange_calendar_xhkg.py
  trading_calendars/exchange_calendar_xidx.py
  trading_calendars/exchange_calendar_xphs.py
  trading_calendars/exchange_calendar_xtai.py
  trading_calendars/lunisolar_holidays.py
  trading_calendars/xkls_holidays.py
Labels: enhancement, pandas_market_calendars

#174 DEV: Add a devcontainer to allow codespaces development
  .devcontainer/Dockerfile
  .devcontainer/base.Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/library-scripts/README.md
  .devcontainer/library-scripts/common-debian.sh
  .devcontainer/library-scripts/node-debian.sh
  .devcontainer/library-scripts/python-debian.sh
  .github/workflows/main.yml
  etc/requirements.txt
Labels: development

#154 ENH: Add breaks to TradingCalendar
  tests/test_trading_calendar.py
  tests/test_xhkg_calendar.py
  trading_calendars/calendar_helpers.py
  trading_calendars/exchange_calendar_xhkg.py
  trading_calendars/trading_calendar.py
  trading_calendars/utils/compat.py
  trading_calendars/utils/preprocess.py
Labels: enhancement

#177 DOC: Expand usage examples in README
  README.md
Labels: documentation

#179 TST: Move off nose and on to pytest
  .github/workflows/main.yml
  etc/requirements.txt
  setup.cfg
  setup.py
  tests/test_calendar_dispatcher.py
  tests/test_trading_calendar.py
  tests/test_xidx_calendar.py
  tests/test_xjse_calendar.py
  tests/test_xkar_calendar.py
Labels: test

#183 TST: Lock requirements properly in tests
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/main.yml
  etc/requirements.in
  etc/requirements.txt
  etc/requirements_dev.in
  etc/requirements_locked.txt
  etc/requirements_locked_old.txt
Labels: test

#184 BENCH: Add CI benchmarking and alerting on regressions
  .devcontainer/devcontainer.json
  .github/workflows/benchmark.yml
  .github/workflows/main.yml
  etc/bench.py
  etc/requirements_dev.in
  etc/requirements_locked.txt
  etc/requirements_locked_old.txt
  setup.py
Labels: bench

#187 BLD: Run CI on master push as well
  .github/workflows/benchmark.yml
  .github/workflows/main.yml
Labels: build

#186 TST: Improve our CI tests speed
  .github/workflows/main.yml
  etc/requirements_dev.in
  etc/requirements_locked.txt
  etc/requirements_locked_old.txt
  setup.py
  tests/test_always_open.py
  tests/test_trading_calendar.py
  tests/test_weekday_calendar.py
  trading_calendars/trading_calendar.py
  trading_calendars/utils/pandas_utils.py
Labels: test

#173 TST: Add py3.9 to test matrix
  .github/dependabot.yml
  .github/workflows/main.yml
  etc/requirements_locked.txt
Labels: test
