Repository quantopian/trading_calendars, pull requests merged in 2020-09, with the labels that each got.

#157 MAINT: Replace US/Eastern with America/New_York
  tests/test_trading_calendar.py
  trading_calendars/exchange_calendar_iepa.py
  trading_calendars/exchange_calendar_xbog.py
  trading_calendars/exchange_calendar_xnys.py
  trading_calendars/us_futures_calendar.py
  trading_calendars/utils/pandas_utils.py
Labels: maintenance

#153 ENH: Add get_calendar_names
  tests/test_calendar_dispatcher.py
  trading_calendars/__init__.py
  trading_calendars/calendar_utils.py
Labels: enhancement

#161 ENH: add additional aliases
  trading_calendars/calendar_utils.py
Labels: enhancement

#166 ENH: Update XLON calendars
  tests/resources/xlon.csv
  trading_calendars/exchange_calendar_xlon.py
Labels: enhancement

#169 ENH: NYSE Calendar prior to 1990
  etc/NYSE-Historical-Closings.pdf
  trading_calendars/exchange_calendar_xnys.py
  trading_calendars/us_holidays.py
Labels: enhancement

#171 BUG: Fix GoodFriday for XCBF
  tests/resources/xcbf.csv
  tests/test_xcbf_calendar.py
  trading_calendars/exchange_calendar_xcbf.py
Labels: bug
